name: "Test CI"

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04]
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.13
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Get dependencies
      run: go get -v -t -d ./...
    - name: Run Installer
      run: |
        go build startup.go
        sudo ./startup
    - name: Export Discord Token
      run: echo ${{ secrets.SINUSBOT_DISCORD_CI }} > .discord
    - name: Run Tests
      run: go test -v startup_test.go
